backend:
  name: git-gateway
  repo: jamesETF/ethical-frenchie
  branch: master

publish_mode: editorial_workflow

media_folder: 'assets/img/blog/'
public_folder: 'img/blog'

collections:
  - name: 'Blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    fields:
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Date', name: 'date', widget: 'date', format: 'YYYY-MM-DD'}
      - {label: 'Category', name: 'category', widget: 'list'}
      - {label: 'Author', name: 'author', widget: 'string'}
      - {label: 'Image', name: 'image', widget: 'image'}
      - {label: 'Description', name: 'description', widget: 'text'}
      - {label: 'Show Date', name: 'showthedate', widget: 'boolean', default: true}
      - {label: 'Draft', name: 'draft', widget: 'boolean', default: true}